# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_group',
        ),
    ]
