# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-28 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='monthjournal',
            options={'verbose_name': 'Monthly Journal', 'verbose_name_plural': 'Mounthly Journals'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Exam Result', 'verbose_name_plural': 'Exams Results'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='gr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='place_exam',
            field=models.CharField(blank=True, max_length=256, verbose_name='Audience'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='science',
            field=models.CharField(max_length=256, verbose_name='Science'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.CharField(max_length=256, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.Student', verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='group',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='group',
            name='place',
            field=models.CharField(blank=True, max_length=256, verbose_name='Audience'),
        ),
        migrations.AlterField(
            model_name='group',
            name='stud',
            field=models.ManyToManyField(blank=True, to='students.Student', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month='date', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='credit',
            field=models.CharField(blank=True, max_length=256, verbose_name='Test(Yes or No)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='exams',
            field=models.ForeignKey(max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='result',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='result',
            name='results_exam',
            field=models.CharField(max_length=256, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='Student'),
        ),
    ]
