# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-13 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170328_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='place_exam',
        ),
        migrations.RemoveField(
            model_name='group',
            name='place',
        ),
        migrations.RemoveField(
            model_name='result',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_born',
        ),
    ]
