# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170413_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='gr',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='stud',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='exams',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='groups',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='results_exam',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='students',
            new_name='student',
        ),
    ]
