# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-14 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170422_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='exam',
            new_name='exams',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='student',
            new_name='students',
        ),
    ]
