# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20170514_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='file',
            field=models.FileField(default=11, upload_to=None),
            preserve_default=False,
        ),
    ]
