# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20170810_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='file',
        ),
    ]
