# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_exam_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='file',
            field=models.FileField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
