# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='SEO Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='styles',
            field=models.TextField(blank=True, verbose_name='CSS styles'),
        ),
    ]
