# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_page_active_link'),
    ]

    operations = [
       
    ]
