# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_page_slug'),
    ]

    operations = [
     
    ]
