# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-27 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20180327_1757'),
    ]

    operations = [
    
    ]
