# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-27 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_page_slug'),
    ]

    operations = [
      
    ]
