# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-27 18:30
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_page_slug'),
    ]

    operations = [
        
    ]
