# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stprofile',
            old_name='mobil_phone',
            new_name='mobile_phone',
        ),
    ]
