# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0002_auto_20170329_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Last Name'),
        ),
    ]
