# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0003_auto_20170329_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='StProfile',
        ),
    ]
