# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='first_name',
            field=models.CharField(default='', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='last_name',
            field=models.CharField(default='', max_length=256, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone',
            field=models.CharField(default='', max_length=12, verbose_name='Mobile Phone'),
        ),
    ]
